{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project',{}) %}

package:
  name: {{ project.get('name') }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_rev : {{ GIT_DESCRIBE_TAG }}
  #git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: "{{ PYTHON }} -m pip install ."

requirements:
  build:
    - python
    - pip
    - wheel
    - setuptools>=45
    - setuptools_scm>=6.2
  host:
    - python
    - numpy
    - scipy
    - h5py
    - matplotlib
  run:
    - python
    - numpy
    - scipy
    - h5py
    - matplotlib

about:
  home: "https://github.com/maimonlab/siffroi"
  summary : {{ project.get('description') }}
  license: {{ project.get('license', {}).get('text') }}
  license_file: ../LICENSE.md

extra:
  recipe-maintainers:
    - StephenThornquist
