{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project',{}) %}

package:
  name: {{ project.get('name') }}
  version: {{ project.get('version') }}

source:
  path: ../
  git_url: ../
  #git_url: https://github.com/maimonlab/siffpy.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: "{{ PYTHON }} -m pip install '.'"

requirements:
  build:
    - python >=3.9
    - pip
    - setuptools>=45
    - setuptools_scm[toml]>=6.2
    - wheel
    - numpy >=1.15
  host:
    - python >=3.9
    - numpy >=1.15
    - scipy
    - h5py
  run:
    - python >=3.9
    - numpy >=1.15
    - scipy
    - h5py

about:
  home: "https://github.com/maimonlab/siffroi"
  summary : {{ project.get('description') }}
  license: {{ project.get('license', {}).get('text') }}
  #license_file: ../LICENSE.md

extra:
  recipe-maintainers:
    - StephenThornquist
